### ISSUE TITLE
importlib_metadata.PackageNotFoundError: No package metadata was found for cython-compiler

### ISSUE THREAD

**Issue by gaamaaresosa** [JessicaTegner/cython-compiler#2]
Raspberry Pi 4
Ubuntu Buster 32bit OS
Python 3.7.3

sudo git clone https://github.com/JessicaTegner/cython-compiler.git
cd cython-compiler
sudo python3 setup.py install

Retried same in 3 different Raspberry Pi 4
Same error at:
sudo cython-compiler -c -e my_main.py

`Traceback (most recent call last):
  File "/usr/bin/cython-compiler", line 33, in <module>
    sys.exit(load_entry_point('cython-compiler==1.0.2', 'console_scripts', 'cython-compiler')())
  File "/usr/bin/cython-compiler", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 947, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 538, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for cython-compiler
`

**Comment by gaamaaresosa** [comment]
@JessicaTegner 
Hats off to this author.
Thank you so much JessicaTegner.
This works great for me.

I experimented 20 similar code and nothing worked for me.
This is really great !

5/5 Stars
*****
